server:
  port: 7000

qiniu:
  config:
    ACCESS_KEY:
    SECRET_KEY:
    bucketName:
    domain:
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qiniuFile?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: a123
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false